import { describe, expect, it } from "vitest";
import { reportDefinitions } from "./reports.js";

describe("report export schemas", () => {
  it("keeps stable column keys for BI and accounting exports", () => {
    expect(
      Object.fromEntries(
        reportDefinitions.map((definition) => [
          definition.id,
          definition.columns.map((column) => column.key)
        ])
      )
    ).toMatchInlineSnapshot(`
      {
        "expiring_lots": [
          "lot_code",
          "sku",
          "item_name",
          "location_name",
          "expires_at",
          "days_until_expiry",
          "quantity_on_hand",
          "uom",
          "qc_status",
        ],
        "held_lots": [
          "lot_code",
          "sku",
          "item_name",
          "location_name",
          "held_quantity",
          "available_quantity",
          "uom",
          "qc_status",
          "hold_reason",
        ],
        "inventory_valuation": [
          "item_type",
          "item_id",
          "sku",
          "item_name",
          "lot_code",
          "location_code",
          "location_name",
          "qc_status",
          "lot_status",
          "available_quantity",
          "reserved_quantity",
          "held_quantity",
          "uom",
          "unit_cost_export",
          "currency",
          "inventory_value_export",
          "expires_at",
        ],
        "production_yield": [
          "batch_code",
          "batch_type",
          "status",
          "order_number",
          "started_at",
          "ended_at",
          "input_quantity",
          "output_quantity",
          "uom",
          "planned_quantity",
          "yield_percent",
          "variance_quantity",
        ],
        "qc_pending": [
          "subject_type",
          "subject_id",
          "record_code",
          "lot_code",
          "sku",
          "qc_type",
          "status",
          "created_at",
          "summary",
        ],
        "recall_trace": [
          "order_number",
          "channel",
          "shopify_order_number",
          "customer_name",
          "customer_email",
          "reseller_name",
          "lot_code",
          "quantity",
          "uom",
          "shipment_number",
          "shipped_at",
          "status",
        ],
        "shopify_sync_health": [
          "topic",
          "shop_domain",
          "webhook_id",
          "status",
          "received_at",
          "processed_at",
          "lag_seconds",
          "error",
        ],
        "stock_aging": [
          "lot_code",
          "sku",
          "item_name",
          "location_name",
          "received_or_made_at",
          "age_days",
          "quantity_on_hand",
          "uom",
          "qc_status",
          "lot_status",
        ],
        "wholesale_sales_export": [
          "order_number",
          "external_order_number",
          "ordered_at",
          "status",
          "customer_name",
          "customer_email",
          "reseller_status",
          "tax_id",
          "sku",
          "product_variant_id",
          "quantity",
          "uom",
          "unit_price",
          "line_total_export",
          "currency",
          "shipment_number",
          "shipped_at",
          "purchase_metadata_source",
          "ledger_account",
        ],
      }
    `);
  });
});
